INSERT INTO players (name) VALUES ('Roger Federer');
INSERT INTO players (name) VALUES ('Rafael Nadal');
INSERT INTO players (name) VALUES ('Novak Djokovic');
INSERT INTO players (name) VALUES ('Andy Murray');
INSERT INTO players (name) VALUES ('Andre Agassi');
INSERT INTO players (name) VALUES ('Pete Sampras');
INSERT INTO players (name) VALUES ('John McEnroe');
INSERT INTO players (name) VALUES ('Boris Becker');
INSERT INTO players (name) VALUES ('Steffi Graf');
INSERT INTO players (name) VALUES ('Serena Williams');
INSERT INTO players (name) VALUES ('Venus Williams');
INSERT INTO players (name) VALUES ('Maria Sharapova');
INSERT INTO players (name) VALUES ('Justine Henin');
INSERT INTO players (name) VALUES ('Kim Clijsters');
INSERT INTO players (name) VALUES ('Martina Hingis');
INSERT INTO players (name) VALUES ('Bjorn Borg');
INSERT INTO players (name) VALUES ('Jimmy Connors');
INSERT INTO players (name) VALUES ('Ivan Lendl');
INSERT INTO players (name) VALUES ('Stefan Edberg');
INSERT INTO players (name) VALUES ('Arantxa Sanchez Vicario');
INSERT INTO players (name) VALUES ('Monica Seles');
INSERT INTO players (name) VALUES ('Lleyton Hewitt');
INSERT INTO players (name) VALUES ('Marat Safin');
INSERT INTO players (name) VALUES ('Gustavo Kuerten');
INSERT INTO players (name) VALUES ('Patrick Rafter');
INSERT INTO players (name) VALUES ('Andy Roddick');
INSERT INTO players (name) VALUES ('Juan Carlos Ferrero');
INSERT INTO players (name) VALUES ('Goran Ivaniševic');
INSERT INTO players (name) VALUES ('Caroline Wozniacki');
INSERT INTO players (name) VALUES ('Ana Ivanovic');

INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 3);
INSERT INTO matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO matches (player1, player2, winner) VALUES (1, 4, 1);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (1, 5, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 6, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 7, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 8, 4);
INSERT INTO matches (player1, player2, winner) VALUES (9, 10, 10);
INSERT INTO matches (player1, player2, winner) VALUES (11, 12, 11);
INSERT INTO matches (player1, player2, winner) VALUES (13, 14, 13);
INSERT INTO matches (player1, player2, winner) VALUES (10, 15, 10);
INSERT INTO matches (player1, player2, winner) VALUES (1, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (2, 5, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 8, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 7, 7);
INSERT INTO matches (player1, player2, winner) VALUES (9, 12, 9);
INSERT INTO matches (player1, player2, winner) VALUES (10, 11, 10);
INSERT INTO matches (player1, player2, winner) VALUES (13, 15, 13);
INSERT INTO matches (player1, player2, winner) VALUES (14, 15, 15);
INSERT INTO matches (player1, player2, winner) VALUES (1, 7, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 8, 2);
INSERT INTO matches (player1, player2, winner) VALUES (16, 17, 16);
INSERT INTO matches (player1, player2, winner) VALUES (18, 19, 18);
INSERT INTO matches (player1, player2, winner) VALUES (16, 18, 16);
INSERT INTO matches (player1, player2, winner) VALUES (17, 19, 19);
INSERT INTO matches (player1, player2, winner) VALUES (20, 21, 20);
INSERT INTO matches (player1, player2, winner) VALUES (22, 23, 22);
INSERT INTO matches (player1, player2, winner) VALUES (24, 25, 25);
INSERT INTO matches (player1, player2, winner) VALUES (26, 27, 26);
INSERT INTO matches (player1, player2, winner) VALUES (28, 29, 28);
INSERT INTO matches (player1, player2, winner) VALUES (30, 1, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 16, 16);
INSERT INTO matches (player1, player2, winner) VALUES (3, 17, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 18, 4);
INSERT INTO matches (player1, player2, winner) VALUES (5, 19, 5);
INSERT INTO matches (player1, player2, winner) VALUES (6, 20, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 21, 7);
INSERT INTO matches (player1, player2, winner) VALUES (8, 22, 8);
INSERT INTO matches (player1, player2, winner) VALUES (9, 23, 9);
INSERT INTO matches (player1, player2, winner) VALUES (10, 24, 10);
INSERT INTO matches (player1, player2, winner) VALUES (11, 25, 11);
INSERT INTO matches (player1, player2, winner) VALUES (12, 26, 12);
INSERT INTO matches (player1, player2, winner) VALUES (13, 27, 13);
INSERT INTO matches (player1, player2, winner) VALUES (14, 28, 14);
INSERT INTO matches (player1, player2, winner) VALUES (15, 29, 15);
INSERT INTO matches (player1, player2, winner) VALUES (1, 9, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 10, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 11, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 12, 4);
INSERT INTO matches (player1, player2, winner) VALUES (5, 13, 5);
INSERT INTO matches (player1, player2, winner) VALUES (6, 14, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 15, 7);
INSERT INTO matches (player1, player2, winner) VALUES (8, 16, 8);
INSERT INTO matches (player1, player2, winner) VALUES (17, 20, 17);
INSERT INTO matches (player1, player2, winner) VALUES (18, 21, 18);
INSERT INTO matches (player1, player2, winner) VALUES (19, 22, 19);
INSERT INTO matches (player1, player2, winner) VALUES (23, 24, 23);
INSERT INTO matches (player1, player2, winner) VALUES (25, 26, 25);
INSERT INTO matches (player1, player2, winner) VALUES (27, 28, 27);
INSERT INTO matches (player1, player2, winner) VALUES (29, 30, 29);
